Pong: Use Hotword Enrollment from NOS 1.5.6
The NOS 2.0.x ones seem to require NOS-specific resources:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nothing/NtFeaturesUtils;

Change-Id: I811c3baba28bedbfcf0a79be540f1c4e9b264db6
Signed-off-by: chandu078 <chandudyavanapelli03@gmail.com>